name: Qodana

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2023.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          linter: jetbrains/qodana-jvm:2023.3
          results-dir: qodana-results
          cache-dir: qodana-cache
          fail-threshold: 10
          fail-on-problems: true

      - name: Upload Qodana Results
        uses: actions/upload-artifact@v3
        with:
          name: qodana-results
          path: qodana-results

      - name: Show Qodana Logs
        run: cat qodana-results/qodana.log
